import Navigation from '@/components/layout/Navigation'
import Footer from '@/components/layout/Footer'

const updatedOn = 'September 26, 2025'

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#06080f] text-white">
      <Navigation />
      <section className="relative py-24">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(88,120,255,0.18),_transparent_65%)]" />
        <div className="relative max-w-5xl mx-auto px-6">
          <div className="mb-12">
            <span className="inline-flex items-center px-4 py-2 rounded-full border border-white/15 bg-white/5 text-xs font-semibold tracking-[0.3em] uppercase text-white/70">
              Privacy
            </span>
            <h1 className="mt-6 text-4xl md:text-5xl font-bold">Privacy Policy</h1>
            <p className="mt-4 text-white/70">Last updated: {updatedOn}</p>
            <p className="mt-6 text-lg leading-relaxed text-white/80">
              This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of
              information when you use the Astrentech website and services. It also explains your privacy rights and how
              the law protects you. By using our services, you agree to the collection and use of information in
              accordance with this policy.
            </p>
          </div>

          <article className="space-y-10 text-white/80 leading-relaxed">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Interpretation and Definitions</h2>
              <p>
                Words with initial capital letters have meanings defined under the following conditions. These
                definitions shall have the same meaning regardless of whether they appear in singular or plural.
              </p>
              <div className="mt-6 space-y-4">
                <p><strong>Account</strong> means a unique account created for you to access our service or parts of our service.</p>
                <p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                <p><strong>Company</strong> (referred to as either “the Company”, “we”, “us” or “our” in this Agreement) refers to Astrentech, C-18, Sector 105, Noida, Uttar Pradesh 201301, India.</p>
                <p><strong>Cookies</strong> are small files placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website among its many uses.</p>
                <p><strong>Country</strong> refers to Uttar Pradesh, India.</p>
                <p><strong>Device</strong> means any device that can access the service such as a computer, cellphone, or digital tablet.</p>
                <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                <p><strong>Service</strong> refers to the website.</p>
                <p><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company.</p>
                <p><strong>Third-party Social Media Service</strong> refers to any website or social network through which a user can log in or create an account to use the service.</p>
                <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself.</p>
                <p><strong>Website</strong> refers to Astrentech, accessible from <a href="https://www.astrentech.com" className="text-accent-secondary hover:underline" target="_blank" rel="noreferrer">https://www.astrentech.com</a>.</p>
                <p><strong>You</strong> means the individual accessing or using the service, or the company or other legal entity on behalf of which such individual is accessing or using the service.</p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Collecting and Using Your Personal Data</h2>
              <h3 className="text-xl font-semibold text-white mt-6 mb-3">Types of Data Collected</h3>
              <p className="mb-4">
                While using our service, we may ask you to provide certain personally identifiable information that can
                be used to contact or identify you. Personally identifiable information may include, but is not limited
                to:
              </p>
              <ul className="list-disc list-inside space-y-1">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>
              <p className="mt-6">
                Usage Data is collected automatically when using the service and may include information such as your
                device&apos;s IP address, browser type, browser version, pages visited, time and date of visit, time
                spent on pages, unique device identifiers, and other diagnostic data.
              </p>
              <p className="mt-4">
                When you access the service by or through a mobile device, we may collect additional information,
                including the type of mobile device, mobile operating system, unique device identifiers, and other
                diagnostic data.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold text-white mb-3">Information from Third-Party Social Media Services</h3>
              <p>
                If you register through a Third-Party Social Media Service, we may collect personal data that is already
                associated with that account, such as your name, email address, activities, or contact list. You may also
                choose to share additional information with us; by doing so, you authorize us to use, share, and store it
                in accordance with this Privacy Policy.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-semibold text-white mb-3">Tracking Technologies and Cookies</h3>
              <p>
                We use cookies and similar tracking technologies to track activity on our service and store certain
                information. Technologies used include cookies, web beacons, and scripts to collect and track information
                to improve and analyze our service.
              </p>
              <p className="mt-4">
                Cookies can be “Persistent” or “Session” cookies. Persistent cookies remain on your device when you go
                offline, while session cookies are deleted when you close your browser. You can instruct your browser to
                refuse cookies, but certain features may not function without them.
              </p>
              <div className="mt-6 space-y-4">
                <p><strong>Necessary / Essential Cookies</strong> help provide the services you request and prevent fraudulent use of accounts.</p>
                <p><strong>Cookies Policy / Notice Acceptance Cookies</strong> identify if users have accepted the use of cookies on the website.</p>
                <p><strong>Functionality Cookies</strong> remember choices you make, such as login details or language preferences.</p>
              </div>
              <p className="mt-4">
                For more information about cookies and how we use them, please refer to the Cookies section below.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Use of Your Personal Data</h2>
              <p>The Company may use personal data for the following purposes:</p>
              <ul className="list-disc list-inside space-y-2 mt-4">
                <li>To provide and maintain our service, including to monitor usage.</li>
                <li>To manage your account as a registered user.</li>
                <li>For the performance of a contract, including purchase or service agreements.</li>
                <li>To contact you with updates, security notifications, or service-related information.</li>
                <li>To provide news, special offers, and information about services similar to those you already use, unless you opt out.</li>
                <li>To manage your requests and support inquiries.</li>
                <li>For business transfers, such as mergers, acquisitions, or sales of assets.</li>
                <li>For other purposes such as data analysis, usage trends, and improving our services.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Sharing of Your Personal Data</h2>
              <ul className="list-disc list-inside space-y-2">
                <li><strong>With Service Providers:</strong> to monitor and analyze service usage or to contact you.</li>
                <li><strong>For Business Transfers:</strong> during negotiations or completion of mergers or asset sales.</li>
                <li><strong>With Affiliates:</strong> requiring them to honor this Privacy Policy.</li>
                <li><strong>With Business Partners:</strong> to offer certain products, services, or promotions.</li>
                <li><strong>With Other Users:</strong> when sharing information in public areas or via social media services.</li>
                <li><strong>With Your Consent:</strong> for any other purpose you authorize.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Retention and Transfer of Your Personal Data</h2>
              <p>
                We retain personal data only for as long as necessary for the purposes outlined in this policy, to comply
                with legal obligations, resolve disputes, and enforce agreements. Usage data is generally retained for a
                shorter period unless needed to improve service security or functionality, or when longer retention is
                required by law.
              </p>
              <p className="mt-4">
                Your information may be transferred to computers located outside your jurisdiction. By providing data,
                you consent to this transfer. We take reasonable steps to ensure your data is treated securely and in
                accordance with this Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Delete Your Personal Data</h2>
              <p>
                You have the right to delete or request assistance in deleting personal data collected about you. You may
                update, amend, or delete information through your account or by contacting us. We may retain certain
                information when necessary to comply with legal obligations.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Disclosure of Your Personal Data</h2>
              <p>
                We may disclose personal data if required by law or in response to valid public authority requests. We may
                also disclose data in good faith to protect our rights, investigate wrongdoing, protect user safety, or
                defend against legal liability.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Security of Your Personal Data</h2>
              <p>
                We strive to use commercially acceptable means to protect personal data, but no method of transmission or
                electronic storage is 100% secure. While we aim to protect your information, we cannot guarantee absolute
                security.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Children&apos;s Privacy</h2>
              <p>
                Our service is not directed to anyone under the age of 13. We do not knowingly collect personal data from
                children under 13. If you believe your child has provided personal data, please contact us so we can
                remove it.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Links to Other Websites</h2>
              <p>
                Our service may contain links to external websites. We have no control over and assume no responsibility
                for the content, privacy policies, or practices of third-party sites. We recommend reviewing the privacy
                policy of every site you visit.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Changes to this Privacy Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. Changes are effective when posted on this page. We
                will notify you of material changes via email or a prominent notice on our service. We encourage you to
                review this Privacy Policy periodically.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Contact Us</h2>
              <p>
                If you have questions about this Privacy Policy, you can contact us by email at{' '}
                <a href="mailto:sales@astrentech.com" className="text-accent-secondary hover:underline">
                  sales@astrentech.com
                </a>
                .
              </p>
            </section>
          </article>
        </div>
      </section>
      <Footer />
    </main>
  )
}

